### ISSUE TITLE
Client can't charge up attack

### ISSUE THREAD

**Issue by pedro0930** [pedro0930/Networked-Tanks#2]
Client cannot charge up attack and health is not synced and everything is fuckkkkkkkkkkked

**Comment by v86861062** [comment]
我應該修好了，試試最新的

**Comment by v86861062** [comment]
~~我測試不出來，都可以charge up attack~~
我知道了，砲彈飛行距離不同
https://youtu.be/UBI1Pits4so


順便一提  HP處理修好了

**Comment by v86861062** [comment]
用髒髒的寫法修好了 D:
